ACTIVE_PROFILE: prod

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letmein

SERVER_PORT: 8086
UI_APP_URL: http://localhost:3000

JWKS_URI: http://localhost:8080/oauth2/jwks

KAFKA_SERVER_URL: http://localhost:9092